buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.4'
    }
}

apply plugin: 'com.android.application'

android {
    compileSdkVersion 9

    defaultConfig {
        applicationId "UrootCheck.app"
        minSdkVersion 9
        targetSdkVersion 9
        versionCode 1
        versionName "1.0"
    }
}
